Repository MelbourneHighSchoolRobotics/ev3sim, pull requests merged in 2020-09, with the labels that each got.

#79 Fix attach print error on main thread.
  ev3sim/attach.py
Labels: bug

#112 Ensure event queue is instantiated regardless of attached code.
  ev3sim/robot.py
  ev3sim/simulation/communication.py
  setup.py
Labels: bug, priority

#129 Version visibility
  ev3sim/__init__.py
  ev3sim/batched_run.py
  ev3sim/sim.py
  ev3sim/single_run.py
  ev3sim/visual/manager.py
  setup.py
Labels: enhancement

#133 Fix url
  ev3sim/__init__.py
  setup.py
Labels: priority

#82 Randomisation
  docs/index.rst
  docs/randomisation.rst
  ev3sim/__init__.py
  ev3sim/batched_run.py
  ev3sim/devices/base.py
  ev3sim/devices/button/base.py
  ev3sim/devices/colour/base.py
  ev3sim/devices/colour/ev3.py
  ev3sim/devices/compass/ev3.py
  ev3sim/devices/infrared/base.py
  ev3sim/devices/motor/base.py
  ev3sim/devices/motor/ev3.py
  ev3sim/devices/ultrasonic/base.py
  ev3sim/devices/ultrasonic/ev3.py
  ev3sim/devices/utils.py
  ev3sim/presets/soccer.py
  ev3sim/presets/soccer_random.yaml
  ev3sim/robot.py
  ev3sim/robots/scripts/controllable.py
  ev3sim/sim.py
  ev3sim/simulation/loader.py
  ev3sim/simulation/randomisation.py
  ev3sim/single_run.py
Labels: documentation, enhancement

#152 Add new version notification to pygame window and program startup.
  ev3sim/single_run.py
  ev3sim/visual/manager.py
  requirements.txt
Labels: enhancement

#156 Ensure ball spawn position is unblocked if possible.
  ev3sim/presets/soccer.py
Labels: bug
