Repository MelbourneHighSchoolRobotics/ev3sim, pull requests merged in 2020-08, with the labels that each got.

#25 Fix change to MHSRobotics.
  README.md
  docs/customisation.rst
  docs/ev3_extensions.rst
  docs/setup.rst
  setup.py
Labels: bug, documentation

#52 Add ev3dev2 binding for compass calibration.
  ev3sim/devices/compass/base.py
  ev3sim/robots/demo.py
Labels: bug

#53 Batched commands
  docs/batched_commands.rst
  docs/index.rst
  ev3sim/attach.py
  ev3sim/batched_commands/communications_demo.yaml
  ev3sim/batched_commands/soccer_competition.yaml
  ev3sim/batched_run.py
  ev3sim/devices/colour/ev3.py
  ev3sim/devices/ultrasonic/ev3.py
  ev3sim/robot.py
  ev3sim/sim.py
  ev3sim/simulation/loader.py
  ev3sim/single_run.py
  setup.py
Labels: documentation, enhancement

#61 Bug window move
  ev3sim/attach.py
  ev3sim/simulation/communication.py
  ev3sim/single_run.py
  ev3sim/visual/manager.py
  ev3sim/visual/objects.py
Labels: bug

#62 Mock print to send logs via gRPC
  ev3sim/attach.py
  ev3sim/batched_run.py
  ev3sim/robots/demo.py
  ev3sim/simulation/comm_schema.proto
  ev3sim/simulation/comm_schema_pb2.py
  ev3sim/simulation/comm_schema_pb2_grpc.py
  ev3sim/simulation/communication.py
Labels: enhancement
